name: hmr
description: Hot Module Replacement system specially designed for command-line Dart applications.
version: 1.0.1
repository: https://github.com/LeadcodeDev/hmr
executables:
  hmr: hmr

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.5.3

dependencies:
  path: ^1.9.1
  glob: ^2.1.3
  mansion: ^0.1.0+1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
